lab_age_key: ENC[AES256_GCM,data:vgFlB1eeJCv+IqVosL/ekOTvazPC1XkLlqHOOr5Dq7+GnwEfwHDTU3Ol7xMhF6slDBTNkxhAYXu0Hosvmak1IoXC0CRqQCZPhN0=,iv:rmfubvvdIh4yx2zJArQQuLutd8VXhNRLPJ+olqXkDOo=,tag:R7PgyYWTmgtkGU7HP53Bwg==,type:str]
worker_user: ENC[AES256_GCM,data:fcR1D38iSEVFlToFl0k=,iv:92b0GI9pAQz9mR9JOdSBjSnHbgRoFwm17o4bMkSe7cs=,tag:nklpgYoWe06rxQFD6XQfog==,type:str]
worker_become_pass: ENC[AES256_GCM,data:Msxhqb7bXe5Rn1b5AHtai20=,iv:7J2wSqdxf2GFGmGaNlCeEPxJM4BtBZTtqWfmpoQFOfY=,tag:t81AlB23oRm+ac8bkTX8JQ==,type:str]
worker_port: ENC[AES256_GCM,data:delrSA==,iv:Udb02qNgcrQK++LxQleoq7TFtpTq6jjhRL8N86qippc=,tag:w2nlzewILCNXPpSWT5v79Q==,type:int]
proxmox_host_ip: ENC[AES256_GCM,data:SVwkk9uYwQ0h7UFV3A==,iv:uFVYzdexUioDZyTxrlWHpmW4D/Ii4yPQ0Rp+ioSFzhk=,tag:LDras1zCjIcdo2OnySlmYw==,type:str]
filesvr_host_ip: ENC[AES256_GCM,data:T0TAJHui13zGW7Wamg==,iv:u5A6VmJZelEbD8KaVg1eFsFC4ff8XTTI3fADhDQD93s=,tag:kSPhaMl0Nor9zksNDvUqnQ==,type:str]
mediasvr_host_ip: ENC[AES256_GCM,data:vymJdF04b486TwrMGw==,iv:jm+NaTH862yX3Zu62pju1IiuaUquVxB4oK5az1s5Nck=,tag:rIy6uWK3YtIN3jJJTW1SkQ==,type:str]
proxy_host_ip: ENC[AES256_GCM,data:S5hU/LEoa8uSC/UCfg==,iv:+sJf7YG0RP6KfohutWIwiZWBLU1KAow51iDXVFjHD1w=,tag:ASiqBPnJjC1+RjxRDuO1RQ==,type:str]
privatevpn_host_ip: ENC[AES256_GCM,data:LkGH5juU6GS4KkHGcQ==,iv:lFX+pJfJ/K+PitmL8LX8ityb20xwW7otXAGQfU4rjLs=,tag:T1UMjqnRnebpG2PwNnQemA==,type:str]
portainer_host_ip: ENC[AES256_GCM,data:2GpX1ABYKmpPiWZ0JA==,iv:ZZUvs2o8m5K4hYnE5cMYCuiGrtq47PEHQe1odFmvx34=,tag:x8kMYpqtCtNNNejwB3wLww==,type:str]
nextcloud_host_ip: ENC[AES256_GCM,data:OzCSf7H+GXY9SClvnQ==,iv:pRt8eIJx6f3Zk0FMU9F+fAaJgfOVZo27BzLSYh32jrA=,tag:qPfzGT49/POqoONw/kiBtQ==,type:str]
gitlab_host_ip: ENC[AES256_GCM,data:2+d476JVwR9wJq0RDA==,iv:T8bXdLvu+i3rcbLTFX3ux3yRAwikbSjXlKkG40rM5vU=,tag:xjOpj5Un/HUqG5Tduz1ueQ==,type:str]
docker_default_user: ENC[AES256_GCM,data:GAoWSuv/bzUagf+trkQ=,iv:dv/4wFtPBQfccDRXz6y7KhHNyNAiaHGFI2buVRxrIH8=,tag:z3+5FC+FLnVAvT9fToZ2qg==,type:str]
ansible_user_password: ENC[AES256_GCM,data:0XQ5C/hUMSdD/O75VMrNR3pgIysSnlE6nqOoTQkSh4EhYQ==,iv:pNxKNcsaFM3qMAUZZVJ8v1vjqhR1Jd94t9r6Vq6RKHQ=,tag:DrJ4sdFD/+Ae0igY58AcTA==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VS84WTZGWmtXQWZ4OU53
            TDUyZ1lQK2JxSzdyK090YitZc243NEJXQkVRCmYvdE82MEVEbkNaTkVIWnpZSE54
            bUNtdlkrVnFWQXJ0OUVlWGlYaXNBOUkKLS0tIGdNTHZNVklUVlhsenR5elk4T29L
            K0MwTUxmUS9Oa3RPbldSMTZlWVFOTjAKVgpuGTiumoJWXV/nexjvRjKfmeN56KWz
            DZcqjWVWB+m792ude/RZB+ZVLfQz1CNBHXxNDKSUFHKbsHmQ24bsCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T07:42:05Z"
    mac: ENC[AES256_GCM,data:HAeEKQzYULS+ZnUVCudq6NsNkfQzBEMiTISsJYt3FJYUFZN95WOMTN/hZJ3ZjuGtWk7KalUfSSaD6WhH7u8fD+PiyZWmK4N2KiQBaESyAaMmCPLAakQpuxTdIG+JpMtzItMVle4wdNLe5dbE+65mdC1OJC+X35h315Hb67f6hF4=,iv:YCYBKr3ch66k6W3/1Ef7ZLqrGARFXUyj17f90Zuduhs=,tag:DOTn/ai+nXq+iow19O6Arw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
