lab_age_key: ENC[AES256_GCM,data:RwhW4TmjqYjMXu0Uls+//Sd4DI3k4iW/1fer1vrWQ6GtrefH8eMbgIzZwLzO3o9oeXRt/9Vp1S7/MMozjl9uaKt39a55N5ns8HQ=,iv:BYbPHMdjUe2IoT9EI9Wp9cKR8a+5WKssmD43LAtMOYI=,tag:zZh+4oz7VbczjmSLEWUfQw==,type:str]
ansible_user: ENC[AES256_GCM,data:NfeZ4JVzLI2IltJ6mBQ=,iv:JQMg4fP7x8TpK2KKLyvXPrwQeOHGs95g+jDovQ+UmNs=,tag:uw0BtEeaiObVxPSEOGYL4w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:PwZ3TymGrwknEWDMa3oZnyU=,iv:VSxPenzDzSRzrQnzFekLJCYhWA+LZTB1FIVi6YyATkI=,tag:jJx4R36K7aiiogNcHRmwjg==,type:str]
ansible_port: ENC[AES256_GCM,data:U5q/sQ==,iv:9L2zO5DtIkuvdELo9jMCQUDYcnihfj1rBA/1DsgidT0=,tag:dsxwEgfanho4lydYnChW6w==,type:int]
proxmox_host_ip: ENC[AES256_GCM,data:T0s84yZZpQEiq1nvjg==,iv:Jsi63gcKq5HovtYfgyx+7/uV75fq5GVmaIdMtog7uRg=,tag:wavyoyGKUt1RsLYMjZS4sg==,type:str]
filesvr_host_ip: ENC[AES256_GCM,data:a6cJOefI3Nc3aBxSUw==,iv:oQLa6I/PEy0oky712xIlpqlMDo0RGTDPzuZ27zMQzGQ=,tag:xySHj2uzzrwIOXBh7KVPLg==,type:str]
mediasvr_host_ip: ENC[AES256_GCM,data:EwTjE4U+VQoIGF3ZRQ==,iv:RYXRmf1K4LE6PYQWdeC8pNjUNtmsUbI7p4L/BfeP3vo=,tag:dfDfJzh9Mmp49y4BQ4apFA==,type:str]
proxy_host_ip: ENC[AES256_GCM,data:i852qE6jCoxB14YFog==,iv:hePd/n9O+cJe3cW5C2RBp0TU2q1CHF6Brr0o0X6Yt+8=,tag:RWu/ebx4mdPjmnuQ1L/Jhw==,type:str]
privatevpn_host_ip: ENC[AES256_GCM,data:zcAcFXmvomyK52Zycg==,iv:9YvTedC3uZJdE/3UA/kD48upvR2mQDQZmKQPBdzU2tU=,tag:XQXSxlirQLsijUfLce+slw==,type:str]
portainer_host_ip: ENC[AES256_GCM,data:u+AjNINfcgbvNjAb1Q==,iv:n++qy4XnYKciomN3SFgfrtX/E3l06p4p4o4WxEm5Kzw=,tag:6wKXJwTGV1KRDgYmbzL3kw==,type:str]
nextcloud_host_ip: ENC[AES256_GCM,data:g1tnMZrU0aQQNvf4XA==,iv:jQ5Qr1/Bs2DFe7eshOl+ncuo6NadtFvhv6xJLxyyEX8=,tag:kZ53+3pCFWE27f9a3sUe1w==,type:str]
gitlab_host_ip: ENC[AES256_GCM,data:96flRyjKsfvAbwmfGg==,iv:NVyS9312ObP/NXj0MtvNTILQJS3HexbkDH7anYiCpcg=,tag:So2R90xr6HmpflYSjzeiBg==,type:str]
docker_default_user: ENC[AES256_GCM,data:PdJmnJQSkUfhCJ7/KIk=,iv:E6iezchTMU1biYiuCqXNryCxeaimv3aEuNZa2WyeZoI=,tag:r5I+BRBKbTkQRmn9BUq1dg==,type:str]
ansible_user_password: ENC[AES256_GCM,data:IBqGCBgc3/eVIZuKC7k4zALerQL1LKYXo2EjLR3YXORmdA==,iv:7i7o0TEpAkVgUwGGW16msjpGjx9D8VK6yoLQB1aB2Ks=,tag:ikgssjA/fwTSBly2samLPg==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWjF4RFJyNzcrV29tcXh2
            TDlVSmVTU2ZHb3FkWmo0MXlrV1lTcCtyWlJvCmI3R0dVOFRzd044R0JxV25WMExq
            bnNKUEY0dHhXN3R5TGNubE9tN29MZWcKLS0tIFhrMVRzKy9yVVpGM285V2pHd0RS
            d1BEaGZrbDBjU1p4TzlIc3RsYlJtMEUKqSNKgGmsatv04X0b29BuD4zywSsX5uPQ
            mLc+Dp8QKcl1IpjXagdEvHt+KHIE+er1nSTZ6AyugXglyiqVVZfnlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T07:13:55Z"
    mac: ENC[AES256_GCM,data:9AVhgJmEXbwiWIx4PlO5/leboHb19eIXaJfxObKqb1NeJVkdYkacNW5q+HU0G3hOhLFLzKCpX6kLSlqu+3+4HFF/YKrIzG2UIHhtGF16Xv7CmKDOfeKHvrlHhU7Kw5+rTA5uUjLcyjaAPRUBpULgw/eUEh91oOtxcSoja60Juoo=,iv:HkpE4U+3It5T1qneZBecGrKY8MbHKFweLhkBnxL6H7Q=,tag:d3Bf9rt01mvSgvg77e8AMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
