lab_age_key: ENC[AES256_GCM,data:fJ5GcAcnYhqL5XHppXu4vhYVn6bA9+WCBJRflAe+Vot1Qzz2U0/g3zJylQXM+/pK+JfwYWH6eAt0zS2WPGWD1m8c9Zi4C3XX9xo=,iv:6U3Hz12H8REB3dDZi4IiyoqEtiogFrgo1+PnbL0V2XA=,tag:jalYelRzQdPthhzT1mu02w==,type:str]
worker_user: ENC[AES256_GCM,data:zFrNBr1/vB6RmD4NQjw=,iv:6nFVq5AQoVo6ASOgXbnZ3YwuMGFMV9hEd5LHTerEpMI=,tag:V7n0eTc/DDWf3r841Oh2BA==,type:str]
worker_become_pass: ENC[AES256_GCM,data:+Nl608WwAAJW/pdvz3OEQw4=,iv:KHx2+Fbm1L2nVKnBaPHWiCkD48y5pZyXIW0QdREE2Og=,tag:jhsjB6ZdCVWi+4YARutIQg==,type:str]
worker_port: ENC[AES256_GCM,data:ZSsDgw==,iv:VzaZeU7cItnZVp8UsQiesqLWGGneu4WtCy5hVzeKd0o=,tag:byBFEB+iB5+HQIvnIwA8hg==,type:float]
proxmox_host_ip: ENC[AES256_GCM,data:WJBCoLjTjvATGU0UIw==,iv:r7IcDZkCccMA8UOCou3XkbPGf1BbrqRlKo7Cql0mauY=,tag:z2yYb+DuCKSO6Ejp0e+Nkw==,type:str]
filesvr_host_ip: ENC[AES256_GCM,data:90p1vjciJVoIjnVNgg==,iv:moRX1D6/bml03ZqcDMNqSOTtFs7nzqybDCy1CfQAc9Y=,tag:gOZg2eSoVGQRTG5e2jOJzg==,type:str]
mediasvr_host_ip: ENC[AES256_GCM,data:orLFUZlb5QNpk2fwRQ==,iv:MXHc0IomDDzI6hZRxxKYz8jMvFd5JcJ6WNA7y1fJHd0=,tag:IjL5aF70mv/KSC01ojoKRA==,type:str]
proxy_host_ip: ENC[AES256_GCM,data:We9qjlQd6pg//jduFg==,iv:ZonB+cBY8qiUmoDa3xG8eN1BQloO62KLlY79s9NrPjo=,tag:fm+9dEQAfGm60zBidS1mMA==,type:str]
privatevpn_host_ip: ENC[AES256_GCM,data:K6NJx/HLqTkgbhrnrQ==,iv:nD2g3PUQTRPvvlfwYQ8GCmi7NQWCICIv1u6Y8hJPMUc=,tag:hKXPxwrkPXhEEAutZzEItA==,type:str]
portainer_host_ip: ENC[AES256_GCM,data:u88T5/n7hI3uisbXhQ==,iv:v/9IKMUPCQ0ZNF+CqgVbofl9uAedRqThXu9NN3Ew5Bc=,tag:rJrvAhhbjty1OeeskaH2vQ==,type:str]
nextcloud_host_ip: ENC[AES256_GCM,data:fQ+OH3VZeqw9q0nRQw==,iv:7/iCRR9aqBAadVGf3aVWBfbKrwOuHhlAWD893o46xQo=,tag:Er16dpr2AxWJC9Q1FYz1+g==,type:str]
gitlab_host_ip: ENC[AES256_GCM,data:G9vbdoYdxoHvTOTcKQ==,iv:QAz/GDNt/gUJ+RjhQMPQ7B+3ONkBYvVQf/+PaACvIbY=,tag:t/kGvvExMr0Gs3595FwVFQ==,type:str]
docker_default_user: ENC[AES256_GCM,data:r5+ez3gV2sxUU3DDeWI=,iv:1VYPqD6lnw2m7IZhF6cQGAbixXr/9FJRCYgW3/wqJGw=,tag:BaibMCLTJbPNYr/o1fxn7A==,type:str]
ansible_user_password: ENC[AES256_GCM,data:hzidMq4ZZzsEcywnE+dR/H9j80v4sfD5miOA7mKI2AIx2A==,iv:CULba7aJdvy2k6ixeghj3lmjr0BcHQpDrDdPjhxtB0E=,tag:RPV86fCcVWM8np6uPphqRg==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZEdoeWlnVUkrMXVKVkEx
            d3lWRFNBeXA5dkdkZmliN0oxRlVjMVZZWHdVCkxVc0JmK1NpSTRBa2ZMUExGbkxP
            eHZrL2RRYXp3K1NiSGNEdUZzMFdQV3cKLS0tIGFiYW4wNlFoSHNPamRPQUNsbkR5
            U2ZvdzFWamE2aHFDeHppVExuazF1ZGsKtAwTe5kTjfnXC/7inb5QZYDliLEgvdOK
            GsbwMSiDUj33B+1cS9XYKiDpwcIt2QBwwEqZkPvLYnoVobLIu418Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T01:24:31Z"
    mac: ENC[AES256_GCM,data:fLBqbe7NSlHporLgeTkAzXXg4qVL81DzQ27XTnc1ZiSOAsZmBcBqejYnYuBBMC85xFMsXca1UjMBpSF9931A4poqlkw8JKYFgqyg7SufyBPmGl/49nYB0BB/Brb7m9dh4T8ufuTD6AvPwfohEYDkMiGUFapanEEi8SWdZNA0p18=,iv:iQaKpWWqBhC+mwdqyzkyNsgDwrVLoAQbIS91/Tknqhk=,tag:4lshh3bpyLpsQM/E/+COIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
