semaphore_admin_password: ENC[AES256_GCM,data:pup5yihhnlR2MPIEdMpMT8idKD977b+UIV370kWwVGA=,iv:LPn/102CEYy1Wj1j0oP+NdgrL9M17498ZgXFPKSqZMs=,tag:i+4Rg8QKCAM7djNaG5OTcw==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSDJjYzkvRjFuZHlnazhy
            U09EajhCQmw5MmJaUy81aXBsWVkzamhuY0U0CkRJS2puNlIzemlURHBFTTBKNzNF
            T3lvSzRYdGJPcllydW5aeXUyQmNJQWsKLS0tIHg0cm1qUlpVcnhaU2hHK3JxMjht
            dWczRGRGb0svVm1uOHQvaTRMdDc4SXMKa1zJPZbMNhpqBos+YkEK5uIEcJBDzr7w
            NiNrptgil+EW2dPy99W8WA1hjpOyPaKlPzD9vP6pzZM5dVD0D6Cr2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T04:41:22Z"
    mac: ENC[AES256_GCM,data:yGUn4zHP/XJ/wLAw1cGtU/yyIqsxjzSqSOWtqopUf6YoA7pI/hPGjaCdsI6xve75oqDBbgNPqGgpb18wcMuA4w7KCWaNdFYbbQ4tZEu+lwx3GXXpGt4F5z3v7BcHgQi/CdmI7RCUwz5ITHiMOx2QkaCJb26CFyLi8XvcGX/XKJY=,iv:DRvCHgd1mAqIlHsMlyV6yJJltxVciU9dLpCc3MxnxKU=,tag:fqrU37V/Y2aV9UE4YYc2Ow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
