semaphore_admin_password: ENC[AES256_GCM,data:pup5yihhnlR2MPIEdMpMT8idKD977b+UIV370kWwVGA=,iv:LPn/102CEYy1Wj1j0oP+NdgrL9M17498ZgXFPKSqZMs=,tag:i+4Rg8QKCAM7djNaG5OTcw==,type:str]
reporter_gotify_token: ENC[AES256_GCM,data:jTQ68/CtrRTdq0eHzfff,iv:2mCAJVUh2IYcpZ+1lClt+EA6voYCsEraD943yYNTDB4=,tag:bgbg06Wktu0pJtXj+Gflrg==,type:str]
reporter_github_token: ENC[AES256_GCM,data:+gqa1VP+wiwQCyx/B5iDFfE5RiqqTzO6JX4echdg0TZXKuIJ1nhwymNCQCBlyGoqIHC26Lbirv2fvw5h4UADlikLpZkt2zTfgaii/3GaU6Aee0ScCpHXNdM3Q8kB,iv:4oT3PM3ROe04UzIIY26B2T0DE+n6GtM61yMBvLwZq1o=,tag:jmX/RRGpQSSzYgpC3WKiWQ==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSDJjYzkvRjFuZHlnazhy
            U09EajhCQmw5MmJaUy81aXBsWVkzamhuY0U0CkRJS2puNlIzemlURHBFTTBKNzNF
            T3lvSzRYdGJPcllydW5aeXUyQmNJQWsKLS0tIHg0cm1qUlpVcnhaU2hHK3JxMjht
            dWczRGRGb0svVm1uOHQvaTRMdDc4SXMKa1zJPZbMNhpqBos+YkEK5uIEcJBDzr7w
            NiNrptgil+EW2dPy99W8WA1hjpOyPaKlPzD9vP6pzZM5dVD0D6Cr2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-05T05:32:54Z"
    mac: ENC[AES256_GCM,data:Rnr9rJv8NDFIQ83N42hghK6+7y8e5jQOAzaNIdxaGSYgaIgrz7ZmQGfneMejHsTb7JtRI2ZUxkkHhAtMeCu61uIpO6QXgWTpHPy7GJwbSESFdGX9QOxqS3domCPvZDY5IjOsEMxUb+Y+iPA2JMnRsfgepVWT3avfeDHLi7s8Rqw=,iv:WZ0SY32Op2lHEe8IjmXqCqJj2YgahPzdKbn8PmHUOvw=,tag:XSYmKelPrIP850Wem3Z6Kg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
