[rpool/ROOT/pve-1]
    use_template = production
    recursive = yes

[ZFS-DATA/proxmox-dataset/images]
    use_template = production
    recursive = yes
    process_children_only = yes

[ZFS-DATA/proxmox-dataset/images/portainer]
    use_template = highchurn

[ZFS-DATA/proxmox-dataset/images/privatevpn]
    use_template = highchurn

[ZFS-DATA/storage-dataset]
    use_template = production
    recursive = yes

#############################
# templates below this line #
#############################

[template_production]
    frequently = 0
    hourly = 12
    daily = 30
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes

[template_highchurn]
    frequently = 0
    hourly = 12
    daily = 14
    monthly = 3
    yearly = 0
    autosnap = yes
    autoprune = yes
