upstream php-handler {
server unix:/run/php/php8.2-fpm.sock;
}
server {
listen 80 default_server;
listen [::]:80 default_server;
server_name Nextcloud-C-Rieger;
root /var/www;
location ^~ /.well-known/acme-challenge {
default_type text/plain;
root /var/www/letsencrypt;
}
location / {
return 301 https://$host$request_uri;
}
}
