secret_files_b64:
    /root/duckdns/duck.sh: ENC[AES256_GCM,data:WNF9c1Id49aEgUyj3F1Sqll2UK5V8ofn6XlfItrHeTph4CUwnIdPmIuxtuFkzR1e1xmNkNMJ/wshGhWa90eAXM4edS2TLBuhPIFgfhqKtuDeWoikw/REHs5BDiN4+8pJH8Yg+aTtWciaLTrm/yRf8RtDFbC+LbrfCjVV0k3leiNwVUP5CgtcI+23KZg3lwzu+oqI0NzC+yR5uYqaS5h8jNhauG5zGDnj+KqRgU6+iuMu9UnEiCxKqw2ZAEM=,iv:8QuMt9gpD3C5CH0c3YePXARN9rUq8w8hca45w7miELg=,tag:QGFUkp5tPc+8xcPe40K1RA==,type:str]
    /opt/caddy/.env: ENC[AES256_GCM,data:gwOHKSmRK80iocdBR4e0qW442KlPIbKTnqu79WO1luoB9xMJOAyqk1MV5gECJNb1fJ2Foy5rDvhbrh8RaFK+KGdvlqBoeoBZwESKTQY+60ko451jENaXI+prlMo6NUvg16GwfEG5+DmkzU1/wuB/hAgbnAsTePCM9h/n3EymrIwLoGgHeLJvGQ==,iv:+hXaucGc+j+roYHMlirPHgV4y+l/tPf2Q+p50dH7lAs=,tag:lEKGou2CKdIvfnBIOaLCeA==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aFNSY0t0cm1DS0I5U2hL
            NWZqV2w5djhNNHRWQlUzL1ZyNkxHZGNTMmowCmhkd2hGRmlvWTRZMHNxMkhOTjJQ
            d2JMVDNpc2g3VHFBc1VGOS9wd2tBTEkKLS0tIHJ0cjFjQ1lvS29EL2Z5dzY3NUNo
            ejZycXAzN21nTTZscTlKQUZCdzdWTDgKvI5m80YlqGgrAi3GJt6S0rHqTcTZIyfB
            yghVhCqT7Ao9av+wZFNad+mphRTknvVWZRswHMvQWjc9lFSFKKc7nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T12:26:25Z"
    mac: ENC[AES256_GCM,data:1BBoKPT71Sj+kzBEr2UhrVNu8jdD4f4V+PwjzXarAiXhS0/my7CxYtys0Y5WnzvgEntyAqXK/jCmyzkHCM0Q+dybGioWQp4cXQREGg8qg8xAQDMAMFO3OiH+FeHnkvbNM8zuR/6jygtKjBozBv4h0qf/qHt8hucfREf1ZVvrdB0=,iv:+lrbAeetOwapUrCOa9sBQktzw4qs6SqFUPn0VexO7iw=,tag:wxIWR/ln+qdBROsn/BuHvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
