secret_files_b64:
    /root/duckdns/duck.sh: ENC[AES256_GCM,data:4pDjI40cXvrjm1oeeRe7l7uLMmmxeR0+HaWYUcqYYP3XpLbqM7acaouqKjYQeMhfrlUsclQ+jkch2Mp0Sbj9gUzwoj3HhFeuL9IIXO77tj88bRZPmO3q3YtyRnSRD15/FDjsqZGhHzhLpKPALM3MKW9uFYgR5q09wlOT9TgE2tyoUa/7pWS/mNeUmPcWmWqsCgYGHRnORVT+tMiWauhVCYZzAanz5FqgXlUU6Gcw45zPUz4j6yD9imDSz5s=,iv:hzV1ug4bdlVHfw+Cf95wWbMwO0xIzE7EvKo+g7/fbCM=,tag:msVyujv/qVUKfWKUCK1PBg==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraFRUNnJuc3h5RXNZcUox
            dGpEZ0VZVkNDMUtCUnE4bW8wdytMeEN3bmc4CkRkWWxkUkZVT0pXVWpjSmFOUHNz
            aVMwRWQwblZHaW81Q1hIQU4wWStMTWcKLS0tIHJxejNsWHcwZkQzY0FCV1Uyb2gz
            d0ZCUlRxMXM0a0ZkQXNxY0ovK0ZibzAKmNqrL5M5nBv38cFBkhHspe2/RXbrqd7W
            1UeLiZKUlGMd/Q3vtrbQpq0DjSxnu004seTfc6NIReuEDmbwQzLeLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T10:03:34Z"
    mac: ENC[AES256_GCM,data:43yVutAVntzDAk6mP/zck86EB6uXFspceMom6uyaVKtWxQpqAOT9IUq0pDANe+YKSkTVpvtxVJLBmHLd+5JDG2BSQm55O9cRM2pdA1O7CQSKUROy1r6PjuHXMB02RIw4z1n23iWyOIRYfjpRopNxUZAAEl0cvXqcHEuo7cnxiMA=,iv:ucegubUOUxa0YX+9lIFRQ0nnOZasD8y4sXBskBq2O10=,tag:sYsOqjfm6HiWxwdKx2YXQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
