secret_files_b64:
    /root/duckdns/duck.sh: ENC[AES256_GCM,data:HLLukNTBC5aJpUS7tLtl7Q4tjtd6jrFZPd9y1tWAwzrN8k0Dcvd6fdQFjurZuEZQa5koM50IbyHOoZs6mNBZLNliyYx7dy+CihFsC/tODJx3tqOiCcqwWGTS8MESc9G5zIViPRx+FODt+mkPMwhevFBxTa81jt1t1f/HBtzViux6/0I5JSUBVr5Cq6SKUW3I4qdKHdlDPW99WO+iwKbnOkNJAwZ6seEiqP4yras3Z/m5ltONp7TsTPCVV74=,iv:s/w73ZDP6PWvcOWFlr0VUprcfsUlg/XY8FJqmhqKA4U=,tag:hheBRXBOWN4k4VOOeoLd0g==,type:str]
    /opt/caddy/.env: ENC[AES256_GCM,data:wwnsCVxPRwbjDuaOcztZDrramWxTiZYYb1H2JtxzWb3h6UuqVvcMYaImASMfsAcS0aDSAc3OFOwy2JXqlB47fBx1oZFqQzpFQaFeC1iB+HLWz5s74cMj7VCoi3/wbLLsuLyTImoqBCK2lMUvo/xjhJmNSQJCzUb+6AGzfWVOylpR+WcWv19xFw==,iv:eSjt3NwnwwckaI9bJume1pfre1pvX78R+K7mDb+RDJw=,tag:PezUbbDUSK3d7LfCJ/97DQ==,type:str]
sops:
    age:
        - recipient: age1wk8xfnvlt0avl0m9pnwd4f0q64qezvlh6d60yzcsm7yjj34mjyjs7udrhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMUJpbTJkNGVyVjladjFM
            NS9NcnRFZDI3Mnl2OE93UEtrditWSGp0RldNCllXL2VYV0RWdURHWE51VzdpdFRm
            NHdMMGpCdjRENVhBVGljMEZoSjhEYk0KLS0tIDNPdHFsMlA1Z3RXZnA4dmhtZUVQ
            UG1JK1NHVVRhMTh6dWhZdUFGVUNTRFkK1gwNS6ZuEvIiHwyogi/t1Dyi4JVQkMXZ
            QtYx+wL+Nc0MYSfZAQzCba1cB0adE9Jcj9Ze7nx0pgSfO4WThm4C4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T08:41:07Z"
    mac: ENC[AES256_GCM,data:Qv8L1Yl1AoZtcP5TKlgjF7G/I+R63gcivhYkBHjd+kT+hqsNArSb0ZzMH8MVBk+juqHZTTMuwsg/FCkoyCXQPtBxpCBbkls0OZ7Ir/FpC2mal9LBhvLbA033onW+lQ8xx0jT5sL6K9zjSiyNnobGQMK9qYqtOhgRWzjG+oByDDA=,iv:qJyivaMPBdx7JkMu4pPin+RireKfjYQIeLTp0FQLekI=,tag:/o8BsVSk3GDJrcP6RSfn4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
